version: "3"
services:
  postgres:
    restart: always
    image: "kartoza/postgis:latest"
    volumes:
      - ./data/postgre/db:/data/db
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=feedthebeast
      - POSTGRES_PASSWORD=6c5b3190cd6772bcaba1d11a21a70192
      - POSTGRES_DB=restartservice
      - DB_HOST=postgres
  web:
    build: .
    ports:
      - "5430:5432"
      #     # - "2020:2020"
  # - "80:3333"
  #   depends_on:
  #     # - redis
  #     - postgres
  # # redis:
  #   image: "redis:alpine"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch
    networks:
      docker-elk:

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    ports:
      - "9200:2020"

networks:
  docker-elk:
    driver: bridge
