version: "3"
services:
  postgres:
    restart: always
    image: "kartoza/postgis:latest"
    volumes:
      - ./data/postgre/db:/data/db
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=feedthebeast
      - POSTGRES_PASSWORD=6c5b3190cd6772bcaba1d11a21a70192
      - POSTGRES_DB=restartservice
      - DB_HOST=postgres
  # web:
  #   build: .
  #   ports:
  #     - "5430:5432"
  #     # - "2020:2020"
  # - "80:3333"
  #   depends_on:
  #     # - redis
  #     - postgres
  redis:
    image: "redis:alpine"
    # elasticsearch:
    #   image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    #   ports:
    #     - 9200:9200
    #   volumes:
    #     - ./share/elasticsearch/data:/usr/share/elasticsearch/data
    #     - ./share/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #   networks: [elastic]
    #   environment:
    #     - discovery.type=single-node
  #   kibana:
  #     image: docker.elastic.co/kibana/kibana-oss:6.3.2
  #     ports:
  #       - 5601:5601
  #     networks: [elastic]
  # networks:
  #   elastic:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
